import Head from 'next/head';
import React from 'react';
import Chapter from '../src/components/Chapter';

export default function IDE() {
    const defaultText = `<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>

    <body>

    </body>

    </html>
    `;
    return (
        <>
            <Head>
                <title>Chapter 1</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Chapter id="getalttext" />
        </>
    );
}
