import Head from 'next/head';
import React from 'react';
import { useEffect, useState } from 'react';
import IdeWrapper from '../src/components/IdeWrapper';
import axios from 'axios';

export default function IDE() {
    const [content, setContent] = useState('');
    const [errors, setErrors] = useState([]);
    const getErrors = (content, monaco) => {
        const chapter = "getalttext";
        axios.post('http://127.0.0.1:5000/chapters/getalttext', {
            code: content,
        }).then(
            ({ data }) => {
                if (data.type === 'error') {
                    setErrors(data.messages);
                }
                else {
                    setErrors([]);
                }
            }).catch(console.error);
    };
    useEffect(() => {
        setContent(`<!DOCTYPE html>
        <html lang="en">

        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Document</title>
        </head>

        <body>

        </body>

        </html>
        `);
    }, [setContent]);
    return (
        <>
            <Head>
                <title>Chapter 1</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{ width: '100%', display: 'flex', justifyContent: "end" }}>
                <div style={{ width: "60%" }}>
                    <IdeWrapper initialContent={content} getErrors={getErrors} errors={errors}></IdeWrapper>
                </div>
            </div>
        </>
    );
}
